# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tpwWebMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 428)
        MainWindow.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color: rgb(0, 85, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 861, 371))
        self.tabWidget.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 90, 181, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 851, 351))
        self.groupBox.setStyleSheet("background-color: rgb(231, 245, 255);\n"
"font: 13pt \"Microsoft YaHei UI\";")
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(240, 110, 291, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(160, 110, 71, 41))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(240, 200, 211, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 290, 211, 41))
        self.pushButton_10.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(11, 11, 11);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label.raise_()
        self.lineEdit.raise_()
        self.pushButton_6.raise_()
        self.pushButton_10.raise_()
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(270, 90, 181, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 290, 211, 41))
        self.pushButton_11.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(11, 11, 11);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(800, 320, 51, 16))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(730, 320, 71, 20))
        self.label_4.setStyleSheet("color: rgb(120, 120, 120);")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(820, 10, 31, 20))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(740, 10, 71, 21))
        self.label_5.setStyleSheet("font: 8pt \"微软雅黑\";\n"
"color: rgb(112, 112, 112);\n"
"")
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(770, 30, 81, 21))
        self.pushButton_7.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"background-color: rgb(197, 197, 197);\n"
"color: rgb(62, 62, 62);\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(640, 60, 211, 261))
        self.plainTextEdit.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color: rgb(75, 75, 75);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 160, 101, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(420, 190, 211, 131))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 30, 451, 31))
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(50, 30, 101, 31))
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_2.raise_()
        self.pushButton_8.raise_()
        self.plainTextEdit.raise_()
        self.pushButton_7.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.lineEdit_2.raise_()
        self.label_4.raise_()
        self.pushButton_9.raise_()
        self.pushButton_3.raise_()
        self.groupBox.raise_()
        self.pushButton_11.raise_()
        self.lineEdit_3.raise_()
        self.label_6.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 200, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.grview_2 = QtWidgets.QGraphicsView(self.tab_2)
        self.grview_2.setGeometry(QtCore.QRect(130, 30, 67, 88))
        self.grview_2.setObjectName("grview_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_3.setGeometry(QtCore.QRect(210, 130, 61, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 130, 61, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.grview = QtWidgets.QGraphicsView(self.tab_2)
        self.grview.setGeometry(QtCore.QRect(50, 30, 67, 88))
        self.grview.setObjectName("grview")
        self.grview_3 = QtWidgets.QGraphicsView(self.tab_2)
        self.grview_3.setGeometry(QtCore.QRect(210, 30, 67, 88))
        self.grview_3.setObjectName("grview_3")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(50, 130, 61, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(50, 200, 111, 41))
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 200, 111, 41))
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(90, 280, 211, 41))
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 471, 181))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(0, 0, 851, 341))
        self.plainTextEdit_3.setStyleSheet("font: 13pt \"微软雅黑\";\n"
"color: rgb(255, 85, 0);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.tab_4)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(0, 0, 851, 341))
        self.plainTextEdit_4.setStyleSheet("font: 10pt \"微软雅黑\";\n"
"color: rgb(91, 91, 91);")
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>对方水电费是胜多负少是的发</p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "启动服务"))
        self.groupBox.setTitle(_translate("MainWindow", "请登录"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "请输入注册码"))
        self.label.setText(_translate("MainWindow", "注册码"))
        self.pushButton_6.setText(_translate("MainWindow", "确定"))
        self.pushButton_10.setText(_translate("MainWindow", "辅助使用说明文档"))
        self.pushButton_9.setText(_translate("MainWindow", "停止服务"))
        self.pushButton_11.setText(_translate("MainWindow", "辅助使用说明文档"))
        self.lineEdit_2.setText(_translate("MainWindow", "5000"))
        self.label_4.setText(_translate("MainWindow", "启动端口："))
        self.label_3.setText(_translate("MainWindow", "new"))
        self.label_5.setText(_translate("MainWindow", "躺平王 6.0"))
        self.pushButton_7.setText(_translate("MainWindow", "更新"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "更新内容如下：\n"
""))
        self.pushButton_8.setText(_translate("MainWindow", "游戏缓存清理"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "1，如果突然出现辅助启动，腾讯助手一直提示环境问题，可以试试清理游戏缓存\n"
"2，使用说明: 打开腾讯助手 ，启动游戏，然后点击 游戏缓存清理即可"))
        self.lineEdit_3.setText(_translate("MainWindow", "https://cloud.189.cn/web/share?code=2ymiieaQRzum（密码：9lnu）"))
        self.label_6.setText(_translate("MainWindow", "辅助下载地址："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "主控"))
        self.pushButton_2.setText(_translate("MainWindow", "3,保存"))
        self.pushButton.setText(_translate("MainWindow", "2,截图"))
        self.pushButton_4.setText(_translate("MainWindow", "刷新"))
        self.pushButton_5.setText(_translate("MainWindow", "1,获取游戏句柄"))
        self.label_2.setText(_translate("MainWindow", "使用说明：\n"
"1：如果英雄不识别，可以通过训练保存图片，就可以识别了\n"
"2，使用步骤如下\n"
"  1，首先点击获取游戏句柄\n"
"  2，游戏进入对战，刷出要识别的英雄\n"
"  3，点击截图，如果出现英雄截图，下面是未识别的，改成你要的英雄名称\n"
"  4，点击保存，如果提示保存成功，说明训练成功了\n"
"  5，注意英雄名称不要写错\n"
"  6，完成后服务端和客户端中止再启动下才能生效"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "训练"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "辅助搞活动，大促销！！！\n"
"1，辅助不绑定机器，可以无限制登录任何一台机器\n"
"2，月卡：30元/50天（开放所有功能）\n"
"3，季卡：90元/180天（开放所有功能）,\n"
"4，永久卡：298元（开放所有功能）\n"
"\n"
"特权：\n"
"季卡：可以远程协助一次解决辅助上的问题\n"
"\n"
"永久卡：终身维护协助，不限制远程协助次数\n"
"\n"
"\n"
"\n"
"辅助会一直维护和更新，欢迎购买\n"
"QQ群：164193436\n"
"答案：躺平王\n"
"\n"
"购买链接：\n"
"App端淘宝购买地址：\n"
"\n"
"【淘宝】https://    m.tb.cn/h.UNxXPof?    tk=SlmFdhAbAR1 CZ3457 「[特惠月卡]塔防精灵辅助智能战斗月卡」 \n"
"点击链接直接打开 或者 淘宝搜索直接打开\n"
"\n"
"PC端购买地址：\n"
"\n"
"https://item.taobao.com/item.htm?spm=a1z10.1-c.w4004-24753504751.4.676d360aJhhZjL&id=698299974933"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "公告"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "更新说明"))
